name: flutter_json
description: Flutter package for rendering JSON data as an interactive hierarchical tree structure with customizable appearance and lazy rendering for improved performance.
version: 0.0.6
repository: "https://github.com/Bungeefan/flutter_json"
topics:
  - json
  - viewer
  - inspector

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  collection: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
